# Generated by Django 5.0.7 on 2024-07-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.CharField(default='Not specified', help_text='Dimensions of the product', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('FRAME', 'Trunk Frame'), ('DRUM', 'Drum Frame'), ('COOLER', 'Cooler Frame')], default='FRAME', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(default='Not specified', help_text='Size of the product', max_length=50),
        ),
    ]
