# Generated by Django 5.0.7 on 2024-08-13 17:38

import aim.validations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='+923214567890', max_length=15, validators=[aim.validations.phone_validation]),
        ),
    ]
